# Generated by Django 4.1 on 2024-07-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Shopcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Shoprating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='SHOPCATEGORY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shopcategory'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory', models.CharField(max_length=100)),
                ('productprice', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalquantity', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('CART', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.cart')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.login')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.user'),
        ),
        migrations.CreateModel(
            name='Assignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('DELIVERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.delivery')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.shop')),
            ],
        ),
    ]
